# Generated by Django 6.0.6 on 2026-06-18 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('insight_type', models.CharField(choices=[('quote', 'Quote'), ('note', 'Note'), ('idea', 'Idea'), ('question', 'Question'), ('reflection', 'Reflection'), ('summary', 'Summary')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('date_captured', models.DateField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='library.knowledgeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'insight_type'], name='journal_ins_user_id_ee520c_idx'), models.Index(fields=['user', 'created_at'], name='journal_ins_user_id_d43514_idx'), models.Index(fields=['user', 'knowledge_item'], name='journal_ins_user_id_d2fa6d_idx')],
            },
        ),
    ]
